# Create the environment:
# mamba env create -f environment.yml
# or if you really want to use conda
# conda env create -f environment.yml

name: aqua-diagnostics
channels:
  - conda-forge
  - nodefaults
# please note that some of these dependencies are made explicit on purpose, but are not directly required by conda/mamba
dependencies:
  - aqua-core>=1.1.0
  # ecmean depends on esmpy binary, so we need to install it first
  - esmpy<=8.9.1
  - pip
  - pip:
    # pip install -e of AQUA itself
    - -e .[core-fdb,tests]
