# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog

# This yaml file will only have either annual or monthly
# Note: Startdate and enddate can be given in 'params'
datasets:
  - catalog: 'climatedt-phase1'
    model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'aqua-timeseries-timeseries'
    regrid: null
    realization: null
    reader_kwargs: null # it can be a dictionary with reader kwargs
    fix: true
  - catalog: 'nextgems4'
    model: 'IFS-FESOM'
    exp: 'historical-1990'
    source: 'aqua-timeseries-timeseries'
    regrid: null
    realization: null
    reader_kwargs: null # it can be a dictionary with reader kwargs
    fix: true

# Reference
references:
  - catalog: 'obs'
    model: 'ERA5'
    exp: 'era5'
    source: 'monthly'
    fix: true

setup:
  loglevel: 'WARNING'

output:
  outputdir: "/work/ab0995/a270260/pre_computed_aqua_analysis/"
  rebuild: true
  save_netcdf: true
  save_format: ['png', 'pdf', 'svg']
  dpi: 300
  create_catalog_entry: true

diagnostics:
  ensemble:
    run: true
    diagnostic_name: 'EnsembleTimeseries'
    variables: ['2t'] # ['ie', 'msl', 'tcc']
    center_time: true # TODO: test center_time
    params:
      default:
        hourly: False
        daily: False
        monthly: True
        annual: True
        startdate: '1990-01-01'
        enddate: '2000-12-31'
        plot_ensemble_members: True
      2t:
        regions: ['global']
        title:
