# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog

# This yaml file will only have either annual or monthly
datasets:
  - catalog: 'climatedt-gen2'
    model: 'IFS-FESOM-10km'
    exp: 'story-nudging-hist'
    source: 'aqua-timeseries-timeseries'
    regrid: null


setup:
  loglevel: 'WARNING'

output:
  outputdir: "./"
  #rebuild: true
  save_netcdf: true
  save_format: ['png', 'pdf', 'svg']
  #dpi: 300

diagnostics:
  ensemble:
    run: true
    diagnostic_name: 'EnsembleTimeseries'
    variable: ['2t',]
    region: ['global',]
    params:
      default:
        startdate_data:
        enddate_data:
        startdate_ref:
        enddate_ref:
    plot_params:
      default:
        title:
        plot_ensemble_members: True
