# Default date for jinja templates for reference datasets:
# ref_startdate, ref_enddate: default reference
# std_startdate, std_enddate: default standard deviation
# std_startdate_ts, std_enddate_ts: default standard deviation for timeseries

default:
  default:
    startdate: "1990-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  radiation:
    startdate: "2001-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  timeseries:
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
scenario:
  default:
    startdate: "1990-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  radiation:
    startdate: "2001-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  timeseries:
    std_startdate: "2020-01-01"
    std_enddate: "2024-12-31"
storyline:
  default:
    startdate: "2017-01-01"
    enddate: "2024-12-31"
    std_startdate: "2000-01-01"
    std_enddate: "2024-12-31"
  radiation:
    startdate: "2001-01-01"
    enddate: "2014-12-31"
    std_startdate: "2000-01-01"
    std_enddate: "2024-12-31"
  timeseries:
    std_startdate: "2020-01-01"
    std_enddate: "2024-12-31"
