machine: lumi
account: project_462000911
username: jvonhar

analysis:
    job_name: aqua-web
    template: aqua-web.job.j2
    partition: small
    nodes: 1
    ntasks_per_node: 128
    time: 04:30:00
    memory: 224G
push:
    job_name: aqua-web.push
    template: aqua-web.push.job.j2
    partition: debug
    nodes: 1
    ntasks_per_node: 1
    time: 00:30:00

logdir_error: /pfs/lustrep4/scratch/project_465002727/jvonhar/log/
logdir_output: /pfs/lustrep4/scratch/project_465002727/jvonhar/log/
aquadir: /pfs/lustrep4/scratch/project_465002727/jvonhar/AQUA
outdir: /pfs/lustrep4/scratch/project_465002727/jvonhar/aqua-analysis/output

catalog: climatedt-phase1
model: IFS-NEMO
exp: historical
source: lra-r100-monthly
realization: r1
